const SCALES={1000:{name:'1kgのはかり',step:5},2000:{name:'2kgのはかり',step:10},4000:{name:'4kgのはかり',step:20}};
const NAVIANS=['https://raw.githubusercontent.com/TT-sensei/navi-character-/main/assets/web/fantasy/monsters/zako/happa-squirrel-leafy.webp','https://raw.githubusercontent.com/TT-sensei/navi-character-/main/assets/web/fantasy/monsters/zako/komorin-little-night-bat.webp','https://raw.githubusercontent.com/TT-sensei/navi-character-/main/assets/web/fantasy/monsters/zako/purun-little-magic-slime.webp'];
let maxWeight=1000,step=5,target=0,anim=null,locked=false;
const $=id=>document.getElementById(id);
document.querySelectorAll('.scale-card').forEach(btn=>btn.addEventListener('click',()=>start(Number(btn.dataset.max))));
$('titleBtn').addEventListener('click',showTitle);$('answerBtn').addEventListener('click',answer);$('answer').addEventListener('keydown',e=>{if(e.key==='Enter')answer()});
function showTitle(){cancelAnimationFrame(anim);locked=false;$('app').classList.add('hidden');$('start').classList.remove('hidden')}
function start(max){maxWeight=max;step=SCALES[max].step;$('scaleLabel').textContent=SCALES[max].name+'　1めもり '+step+'g';$('start').classList.add('hidden');$('app').classList.remove('hidden');buildDial();spawn()}
function buildDial(){const svg=$('dialSvg');svg.innerHTML='';const NS='http://www.w3.org/2000/svg',cx=310,cy=302,r=245,intervals=maxWeight/step;
const arc=document.createElementNS(NS,'path');arc.setAttribute('d',`M ${cx-r} ${cy} A ${r} ${r} 0 0 1 ${cx+r} ${cy}`);arc.setAttribute('fill','none');arc.setAttribute('stroke','#cbd3dc');arc.setAttribute('stroke-width','3');svg.appendChild(arc);
for(let i=0;i<=intervals;i++){const a=Math.PI-(i/intervals)*Math.PI,major=i%20===0,mid=i%10===0,inner=r-(major?28:mid?20:13),x1=cx+Math.cos(a)*inner,y1=cy-Math.sin(a)*inner,x2=cx+Math.cos(a)*r,y2=cy-Math.sin(a)*r;
const line=document.createElementNS(NS,'line');line.setAttribute('x1',x1);line.setAttribute('y1',y1);line.setAttribute('x2',x2);line.setAttribute('y2',y2);line.setAttribute('stroke','#344054');line.setAttribute('stroke-width',major?'3':mid?'2':'1.2');svg.appendChild(line);
if(major){const text=document.createElementNS(NS,'text');text.setAttribute('x',cx+Math.cos(a)*(r-52));text.setAttribute('y',cy-Math.sin(a)*(r-52)+6);text.setAttribute('text-anchor','middle');text.textContent=Math.round((i/intervals)*maxWeight);text.setAttribute('font-size','19');text.setAttribute('font-weight','800');text.setAttribute('fill','#24344f');svg.appendChild(text)}}const unit=document.createElementNS(NS,'text');unit.setAttribute('x',cx);unit.setAttribute('y','54');unit.setAttribute('text-anchor','middle');unit.textContent='g';unit.setAttribute('font-size','20');unit.setAttribute('font-weight','800');unit.setAttribute('fill','#667085');svg.appendChild(unit)}
function spawn(){cancelAnimationFrame(anim);locked=false;$('answer').value='';$('answer').disabled=true;$('answerBtn').disabled=true;$('nextBtn').classList.add('hidden');$('feedback').textContent='';$('feedback').className='feedback';$('message').textContent='ナビアンが はかりにのったよ。';$('message').className='message show';target=(Math.floor(Math.random()*(maxWeight/step-1))+1)*step;$('navian').src=NAVIANS[Math.floor(Math.random()*NAVIANS.length)];$('navian').className='navian entering';requestAnimationFrame(()=>$('navian').classList.add('on-pan'));const from=-86,to=weightAngle(target),duration=900,t0=performance.now();function tick(t){const p=Math.min(1,(t-t0)/duration),e=1-Math.pow(1-p,3),deg=from+(to-from)*e;setPointer(deg);if(p<1)anim=requestAnimationFrame(tick);else{setPointer(to);locked=true;$('answer').disabled=false;$('answerBtn').disabled=false;$('message').textContent='針が止まったよ。目盛を読もう。';$('answer').focus()}}anim=requestAnimationFrame(tick)}
function weightAngle(weight){return -90+(weight/maxWeight)*180}
function setPointer(deg){$('pointer').style.transform=`rotate(${deg}deg)`}
function answer(){if(!locked)return;const value=Number($('answer').value);if(!Number.isFinite(value))return;locked=false;$('answer').disabled=true;$('answerBtn').disabled=true;if(value===target){$('feedback').textContent='ぴったり！ '+target+'g';$('feedback').className='feedback correct';$('message').textContent='目盛をしっかり読めたね。'}else{$('feedback').textContent='正解は '+target+'g。針の先と目盛をもう一度見よう。';$('feedback').className='feedback wrong';$('message').textContent='正しい目盛はここだよ。'}$('nextBtn').classList.remove('hidden')}
$('nextBtn').addEventListener('click',spawn);