let mode='hunter',step=30,target=0,pos=0,anim=null,locked=false,timerId=null,timeLeft=60,score=0,stats=loadStats(),protractorVisualTarget=0,currentNavian=null;
const $=id=>document.getElementById(id),C={cx:200,cy:200,r:155,navR:132};
function loadStats(){try{return JSON.parse(localStorage.getItem('angleHunter.stats.v2'))||{attempts:0,correct:0,weak:{}}}catch(e){return{attempts:0,correct:0,weak:{}}}}function saveStats(){localStorage.setItem('angleHunter.stats.v2',JSON.stringify(stats))}function recordNavianGet(monsterId){try{const key='angleHunter.navianGets.v2';const gets=JSON.parse(localStorage.getItem(key))||{};if(!monsterId)return;gets[monsterId]=(Number(gets[monsterId])||0)+1;localStorage.setItem(key,JSON.stringify(gets))}catch(e){}}function point(deg,r=C.navR){const a=-deg*Math.PI/180;return{x:C.cx+Math.cos(a)*r,y:C.cy+Math.sin(a)*r}}function sectorPath(deg,r=104){if(deg<=0)return `M ${C.cx} ${C.cy} L ${C.cx+r} ${C.cy} Z`;const a=-deg*Math.PI/180,x=C.cx+Math.cos(a)*r,y=C.cy+Math.sin(a)*r,large=deg>180?1:0;return `M ${C.cx} ${C.cy} L ${C.cx+r} ${C.cy} A ${r} ${r} 0 ${large} 0 ${x} ${y} Z`}function setSector(deg,strong=false){const e=$('angleSector');if(!e)return;e.setAttribute('d',sectorPath(deg));e.setAttribute('class',strong?'angle-sector active':'angle-sector')}
function drawField(){let s='<svg viewBox="0 0 400 400" width="100%" height="100%" aria-hidden="true">';s+='<path id="angleSector" class="angle-sector" d="'+sectorPath(0)+'"/><circle cx="200" cy="200" r="155" fill="none" stroke="#24344f" stroke-width="2.5" opacity=".65"/>';for(let d=0;d<360;d+=step){const a=-d*Math.PI/180,major=d%30===0,r1=major?143:150,r2=160,x1=200+Math.cos(a)*r1,y1=200+Math.sin(a)*r1,x2=200+Math.cos(a)*r2,y2=200+Math.sin(a)*r2;s+=`<line x1="${x1}" y1="${y1}" x2="${x2}" y2="${y2}" stroke="#24344f" stroke-width="${major?3.5:2}" opacity="${major?'.9':'.62'}" stroke-linecap="round"/>`;if(major)s+=`<text x="${200+Math.cos(a)*128}" y="${200+Math.sin(a)*128+5}" text-anchor="middle" font-size="13" font-weight="800" fill="#24344f">${d}°</text>`}s+='</svg>';$('field').innerHTML=s}
function buildAngles(){const box=$('angles');box.innerHTML='';if(step===15){for(let d=0;d<360;d+=15){const b=document.createElement('button');b.type='button';b.className='angle';b.textContent=d+'°';const choose=ev=>{ev.preventDefault();answer(d,b)};b.addEventListener('pointerup',choose);box.appendChild(b)}return}for(let d=0;d<360;d+=step){const b=document.createElement('button');b.type='button';b.className='angle';b.textContent=d+'°';const choose=ev=>{ev.preventDefault();answer(d,b)};b.addEventListener('pointerup',choose);box.appendChild(b)}}function setLine(el,deg,len=C.r){el.style.width=len+'px';el.style.transform=`rotate(${-deg}deg)`}function posNav(deg){const p=point(deg);$('navian').style.left=p.x/400*100+'%';$('navian').style.top=p.y/400*100+'%'}function resetLines(){['aim','correctLine','net'].forEach(id=>{const e=$(id);e.className=id;e.style.width='0';e.style.opacity='0'});setSector(0,false);$('message').className='message';$('message').textContent=''}function randomNav(){
  // モードごとに出現するナビアンを固定：
  // 30°モード＝ナビアン、15°モード＝エボナビ、1°モード＝ボスナビ
  const level=step===30?1:step===15?2:3;
  const pool=MONSTERS.filter(m=>m.level===level);
  currentNavian=pool[Math.floor(Math.random()*pool.length)];
  return currentNavian;
}
function spawn(){randomNav();cancelAnimationFrame(anim);anim=null;locked=false;resetLines();$('next').style.display='none';$('navian').className='navian';$('navian').src=MONSTER_BASE+currentNavian.path+'/'+currentNavian.file;target=Math.floor(Math.random()*(360/step))*step;posNav(0);let duration=850+target*3.1;if(mode==='challenge')duration=420;$('navian').classList.add('running');$('aim').classList.add('show');setLine($('aim'),0,205);setSector(0,false);const t0=performance.now();function tick(t){const p=Math.min(1,(t-t0)/duration),e=1-Math.pow(1-p,2),deg=target*e;posNav(deg);setLine($('aim'),deg,205);setSector(deg,false);if(p<1)anim=requestAnimationFrame(tick);else{$('navian').classList.remove('running');posNav(target);setLine($('aim'),target,205);setSector(target,true);locked=true;anim=null}}anim=requestAnimationFrame(tick)}
function playSound(id){try{window.eduSound?.(id)}catch(e){}}function feedback(text,kind){const m=$('message');m.textContent=text;m.className='message show '+kind}function answer(choice,button){if(!locked)return;locked=false;stats.attempts++;const ok=choice===target;if(ok){stats.correct++;score++;recordNavianGet(currentNavian.id);playSound('correct');button.classList.add('correct');$('navian').classList.add('caught');setLine($('net'),choice,C.r);$('net').classList.add('right');setSector(target,true);feedback('GET！ '+target+'°','hit')}else{playSound('wrong');stats.weak[target]=(stats.weak[target]||0)+1;button.classList.add('wrong');setLine($('net'),choice,C.r);$('net').classList.add('wrong');setLine($('correctLine'),target,C.r);$('correctLine').classList.add('show');setSector(target,true);feedback('おしい！ 正解は '+target+'°','miss')}saveStats();renderStats();if(mode==='challenge'){setTimeout(()=>{if(timeLeft>0)spawn()},ok?260:1000)}else{$('next').style.display='inline-flex'}}
function renderStats(){$('attempts').textContent=stats.attempts;$('correct').textContent=stats.correct;$('rate').textContent=stats.attempts?Math.round(stats.correct/stats.attempts*100)+'%':'0%';$('score').textContent=score;$('timer').textContent=timeLeft;$('timer').classList.toggle('hidden',mode!=='challenge');$('stepLabel').textContent=step===1?'1°刻み':step+'°'}
function startGame(newMode,newStep=30){playSound(newMode==='challenge'?'start':'start');mode=newMode;step=Number(newStep);if(mode==='book'){openBook();return}if(step===1){startProtractor();return}clearInterval(timerId);timerId=null;$('start').classList.add('hidden');$('result').classList.add('hidden');$('app').classList.remove('hidden');$('normalGame').classList.remove('hidden');$('protractorGame').classList.add('hidden');$('modeLabel').textContent=mode==='challenge'?'チャレンジ':'ハンター';$('recordTitle').textContent=mode==='challenge'?'今回の記録':'きろく';$('challengePanel').classList.toggle('hidden',mode!=='challenge');$('brandHint').textContent='ナビアンが止まった角度を見抜こう';score=0;timeLeft=60;renderStats();drawField();buildAngles();if(mode==='challenge'){renderStats();timerId=setInterval(()=>{timeLeft--;renderStats();const timerEl=$('timer');if(timerEl)timerEl.classList.toggle('urgent',timeLeft<=10&&timeLeft>0);if(timeLeft<=0){clearInterval(timerId);timerId=null;if(timerEl){timerEl.textContent='0';timerEl.classList.remove('urgent')}finishChallenge()}},1000);}spawn()}
function finishChallenge(){playSound('clear');cancelAnimationFrame(anim);anim=null;locked=false;$('navian').className='navian';$('resultNumber').textContent=score;$('result').classList.remove('hidden')}
function buildProtractor(){const ticks=$('protractorTicks'),nums=$('protractorNumbers');ticks.innerHTML='';nums.innerHTML='';const cx=400,cy=370,r=286,inner=268;for(let d=0;d<=180;d++){const a=Math.PI-d*Math.PI/180,major=d%10===0,mid=d%5===0,r1=major?inner-12:mid?inner-7:inner-3,r2=r,x1=cx+Math.cos(a)*r1,y1=cy-Math.sin(a)*r1,x2=cx+Math.cos(a)*r2,y2=cy-Math.sin(a)*r2,line=document.createElementNS('http://www.w3.org/2000/svg','line');line.setAttribute('x1',x1);line.setAttribute('y1',y1);line.setAttribute('x2',x2);line.setAttribute('y2',y2);line.setAttribute('stroke',major?'#344054':mid?'#667085':'#98a2b3');line.setAttribute('stroke-width',major?'2.5':mid?'1.7':'1');ticks.appendChild(line);if(major){const t=document.createElementNS('http://www.w3.org/2000/svg','text'),nr=inner-29;t.setAttribute('x',cx+Math.cos(a)*nr);t.setAttribute('y',cy-Math.sin(a)*nr+5);t.setAttribute('text-anchor','middle');t.setAttribute('font-size','16');t.setAttribute('fill','#24344f');t.textContent=d;nums.appendChild(t);const t2=document.createElementNS('http://www.w3.org/2000/svg','text'),nr2=inner-57;t2.setAttribute('x',cx+Math.cos(a)*nr2);t2.setAttribute('y',cy-Math.sin(a)*nr2+5);t2.setAttribute('text-anchor','middle');t2.setAttribute('font-size','15');t2.setAttribute('fill','#3478c8');t2.setAttribute('opacity','.72');t2.textContent=180-d;nums.appendChild(t2)}}}
function proPoint(deg,r=320){const a=Math.PI-deg*Math.PI/180;return{x:400+Math.cos(a)*r,y:370-Math.sin(a)*r}}
function setProtractorLine(deg){const line=$('protractorRay'),correct=$('protractorCorrectLine'),len=330;line.style.left='50%';line.style.bottom='13%';line.style.width=len+'px';line.style.transform=`rotate(${deg-180}deg)`;correct.style.left='50%';correct.style.bottom='13%';correct.style.width=len+'px';correct.style.transform=`rotate(${deg-180}deg)`}
function setProtractorArc(startDeg,endDeg){const arc=$('protractorAngleArc');if(!arc)return;const r=92,rad=d=>(Math.PI-d*Math.PI/180),pt=d=>({x:400+Math.cos(rad(d))*r,y:370-Math.sin(rad(d))*r}),a=pt(startDeg),b=pt(endDeg),sweep=endDeg>startDeg?1:0;arc.setAttribute('d',`M ${a.x} ${a.y} A ${r} ${r} 0 0 ${sweep} ${b.x} ${b.y}`)}
function protractorPos(deg){const navRadius=currentNavian?.level===3?352:320;const p=proPoint(deg,navRadius);$('protractorNavian').style.left=p.x/800*100+'%';$('protractorNavian').style.top=p.y/424*100+'%';setProtractorLine(deg);setProtractorArc(window.protractorArcStart??0,deg)}
function startProtractor(){clearInterval(timerId);timerId=null;cancelAnimationFrame(anim);anim=null;locked=false;$('start').classList.add('hidden');$('result').classList.add('hidden');$('app').classList.remove('hidden');$('normalGame').classList.add('hidden');$('protractorGame').classList.remove('hidden');$('brandHint').textContent=mode==='challenge'?'60秒で分度器を読んでつかまえよう':'分度器の目盛を読んで、1°単位で答えよう';$('stepLabel').textContent='1°刻み';$('recordTitle').textContent=mode==='challenge'?'チャレンジ（分度器）':'ハンター（分度器）';$('challengePanel').classList.toggle('hidden',mode!=='challenge');if(mode==='challenge'){score=0;timeLeft=60;renderStats();timerId=setInterval(()=>{timeLeft--;renderStats();if(timeLeft<=0){clearInterval(timerId);timerId=null;finishChallenge()}},1000)}else{renderStats()}buildProtractor();requestAnimationFrame(spawnProtractor)}
function spawnProtractor(){randomNav();locked=false;$('protractorNext').style.display='none';$('degreeInput').value='';$('degreeInput').className='degree-input';$('degreeSubmit').disabled=true;$('protractorNavian').className='protractor-navian';$('protractorRay').className='protractor-ray show';$('protractorCorrectLine').className='protractor-correct-line';$('protractorNavian').src=MONSTER_BASE+currentNavian.path+'/'+currentNavian.file;target=Math.floor(Math.random()*179)+1;const fromLeft=Math.random()<.5;protractorVisualTarget=fromLeft?target:180-target;window.protractorArcStart=fromLeft?0:180;$('protractorLabel').textContent=fromLeft?'左の0°から読もう':'右の0°から読もう';$('protractorLabel').className='protractor-label';setProtractorArc(window.protractorArcStart,window.protractorArcStart);$('protractorNavian').classList.add('running');const t0=performance.now(),duration=1050;function tick(t){const p=Math.min(1,(t-t0)/duration),e=1-Math.pow(1-p,2),deg=window.protractorArcStart+(protractorVisualTarget-window.protractorArcStart)*e;protractorPos(deg);if(p<1)anim=requestAnimationFrame(tick);else{locked=true;anim=null;protractorPos(protractorVisualTarget);$('protractorNavian').classList.remove('running');$('degreeSubmit').disabled=false}}anim=requestAnimationFrame(tick)}
function answerProtractor(){if(!locked)return;const input=$('degreeInput'),value=Number(input.value);if(!Number.isInteger(value)||value<0||value>180)return;locked=false;$('degreeSubmit').disabled=true;stats.attempts++;const ok=Math.abs(value-target)<=1;if(ok){stats.correct++;score++;recordNavianGet(currentNavian.id);playSound('correct');input.classList.add('protractor-correct');$('protractorNavian').classList.add('caught');$('protractorCorrectLine').className='protractor-correct-line show';setProtractorLine(protractorVisualTarget);setProtractorArc(window.protractorArcStart,protractorVisualTarget);feedbackPro('ぴったり！ '+target+'°','hit')}else{playSound('wrong');stats.weak[target]=(stats.weak[target]||0)+1;input.classList.add('protractor-wrong');$('protractorCorrectLine').className='protractor-correct-line show';setProtractorLine(protractorVisualTarget);setProtractorArc(window.protractorArcStart,protractorVisualTarget);feedbackPro('正解は '+target+'°。目盛をもう一度確認しよう','miss')}saveStats();renderStats();if(mode==='challenge'){setTimeout(()=>{if(timeLeft>0)spawnProtractor()},ok?260:380)}else $('protractorNext').style.display='inline-flex'}function feedbackPro(text,kind){$('protractorLabel').textContent=text;$('protractorLabel').className='protractor-label '+kind}
function title(){clearInterval(timerId);timerId=null;cancelAnimationFrame(anim);anim=null;locked=false;$('app').classList.add('hidden');$('result').classList.add('hidden');$('book').classList.add('hidden');$('start').classList.remove('hidden')}function openBook(){playSound('notify');clearInterval(timerId);timerId=null;cancelAnimationFrame(anim);anim=null;locked=false;$('start').classList.add('hidden');$('app').classList.add('hidden');$('book').classList.remove('hidden');const g=$('bookGrid');g.innerHTML='';const groups=[{label:'レベル1　ナビアン',level:1},{label:'レベル2　エボナビ',level:2},{label:'レベル3　ボスナビ',level:3}];for(const group of groups){const h=document.createElement('h3');h.className='book-group-title';h.textContent=group.label;g.appendChild(h);const wrap=document.createElement('div');wrap.className='book-group-grid';MONSTERS.filter(m=>m.level===group.level).forEach(m=>{const c=document.createElement('div');c.className='book-card';c.innerHTML=`<img src="${MONSTER_BASE+m.path+'/'+m.file}" alt="${m.name}"><span>${m.name}</span><small>Lv.${m.level}</small>`;wrap.appendChild(c)});g.appendChild(wrap)}}
document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',ev=>{ev.stopPropagation();startGame(b.dataset.mode,b.dataset.step||30)}));$('next').onclick=()=>{playSound('decide');spawn()};$('protractorNext').onclick=()=>{playSound('click');spawnProtractor()};$('titleBtn').onclick=()=>{playSound('click');title()};$('resultTitle').onclick=()=>{playSound('click');title()};$('again').onclick=()=>startGame('challenge',step);$('bookBack').onclick=()=>{playSound('click');title()};$('degreeSubmit').onclick=()=>{playSound('decide');answerProtractor()};$('degreeInput').addEventListener('keydown',e=>{if(e.key==='Enter')answerProtractor()});window.eduSoundUpdate=()=>{const b=$('soundBtn');if(b)b.textContent=window.eduSoundIsMuted?.()?'🔇 音':'🔊 音'};
$('soundBtn')?.addEventListener('click',()=>window.eduSoundToggle?.());
window.eduSoundUpdate();
renderStats();

// STANDALONE_BOOK_LINK
document.addEventListener('click',function(e){
  const b=e.target.closest('.book-mode');
  if(b){e.preventDefault();e.stopImmediatePropagation();location.href='book.html';}
},true);

currentNavian=randomNav();
